Update `dotfile_update` script

diff --git a/bin/.bin/dotfile_update b/bin/.bin/dotfile_update
--- a/bin/.bin/dotfile_update
+++ b/bin/.bin/dotfile_update
@@ -2,10 +2,42 @@
 
 set -e
 
-function do_dotfile_update () {
-    cd "$DOTFILE_HOME"
-    echo "\$" $0
-    # git pull --rebase --stat origin master
+cd "$DOTFILE_HOME"
+
+function do_dotfile_clean () {
+    git_dirty=$(git clean -dfn)
+
+    if [ -n "$git_dirty" ]; then
+        c.warn "Detected a dirty dotifle directory.\ndotfile could not update without removing the following files and folder:"
+        echo $git_dirty
+
+        read -p "Do you wish to clean up dotfile directory (y/n)?" choice
+        case "$choice" in 
+            y|Y|yes|Yes|YES ) 
+                git clean -df
+                c.success "Successfully clean dotfile directory!"
+            ;;
+            n|N|no|No|NO ) 
+                exit 1 
+            ;;
+            * )
+                main 
+            ;;
+        esac
+    fi
 }
 
-do_dotfile_update
+function do_dotfile_update () {
+    git pull --rebase --stat origin master
+}
+
+function main () {
+    if do_dotfile_clean; then
+        do_dotfile_update
+    else
+        c.error "Oops! Something went wrong. Failed to update dotfile!"
+    fi
+}
+
+# Entrypoint
+main;
